repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    # add max line length to 120
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--line-length=120]